version: '3'
services:
  server:
    depends_on:
      - micro-postgres
      - micro-kafka
    build:
      context: .
    container_name: micro-server
    hostname: micro-server
    networks:
      - micro-net
    ports:
      - "8090:8090"
    volumes:
      - micro-server-volume:/app
    environment:
      - PGUSER=${PGUSER:-postgres}
      - PGPASSWORD=${PGPASSWORD:?database password not set}
      - PGHOST=${PGHOST:-micro-postgres}
      - PGPORT=${PGPORT:-5490}
      - PGDATABASE=${PGDATABASE:-postgres}
      - BOOTSTRAP_SERVERS=${BOOTSTRAP_SERVERS:-kafka:9092}
    deploy:
      restart_policy:
        condition: on-failure
  micro-postgres:
    image: postgres
    container_name: micro-postgres
    hostname: micro-postgres
    networks:
      - micro-net
    ports:
      - "5490:5490"
    volumes:
      - micro-postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD:?database password not set}
    deploy:
      restart_policy:
        condition: on-failure
  micro-zookeeper:
    image: confluentinc/cp-zookeeper:7.6.2
    hostname: micro-zookeeper
    container_name: micro-zookeeper
    ports:
      - "2190:2190"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2190
    networks:
      - micro-net
  micro-kafka:
    image: confluentinc/cp-kafka:7.6.2
    hostname: micro-kafka
    container_name: micro-kafka
    ports:
      - "9090:9090"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=micro-zookeeper:2190
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://micro-kafka:9090
    networks:
      - micro-net
    depends_on:
      - micro-zookeeper


volumes:
  micro-server-volume:
  micro-postgres-volume:

networks:
  micro-net:
    driver: bridge