services:
  server:
    depends_on:
      - micro-postgres
      - micro-kafka
    build:
      context: .
    container_name: micro-server
    hostname: micro-server
    networks:
      - micro-net
    ports:
      - 8090:8090
    volumes:
      - micro-server-volume:/app
    environment:
      - PGUSER=${PGUSER:-postgres}
      - PGPASSWORD=${PGPASSWORD:?database password not set}
      - PGHOST=${PGHOST:-micro-postgres}
      - PGPORT=${PGPORT:-5490}
      - PGDATABASE=${PGDATABASE:-postgres}
      - BOOTSTRAP_SERVERS=${BOOTSTRAP_SERVERS:-kafka:9092}
    deploy:
      restart_policy:
        condition: on-failure
  micro-postgres:
    image: postgres
    container_name: micro-postgres
    hostname: micro-postgres
    networks:
      - micro-net
    ports:
      - 5490:5490
    volumes:
      - micro-postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD:?database password not set}
    deploy:
      restart_policy:
        condition: on-failure
  micro-zookeeper:
    image: confluentinc/cp-zookeeper:7.6.2
    hostname: micro-zookeeper
    container_name: micro-zookeeper
    ports:
      - 2190:2190
    environment:
      - ZOOKEEPER_CLIENT_PORT=2190
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_SERVERS=zoo1:2888:3888
  micro-kafka:
    image: confluentinc/cp-kafka:7.6.2
    hostname: micro-kafka
    container_name: micro-kafka
    ports:
      - 9090:9090
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=micro-zookeeper:2190
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9090,PLAINTEXT_HOST://localhost:29090
      - KAFKA_METRIC_REPORTERS=io.confluent.metrics.reporter.ConfluentMetricsReporter
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_AUTO_CREATE_TOPICS_ENABLED=true
      - CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS=kafka:9090
      - CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT=micro-zookeeper:2190
      - CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS=1
      - CONFLUENT_METRICS_ENABLE=true
      - CONFLUENT_SUPPORT_CUSTOMER_ID=anonymous
    depends_on:
      - micro-zookeeper


volumes:
  micro-server-volume:
  micro-postgres-volume:

networks:
  micro-net:
    driver: bridge